// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDto } from "./ApprovalDto";

export type ApprovalsPage = { 
/**
 * Pendientes de todas las sesiones, más antiguas primero.
 */
approvals: Array<ApprovalDto>, };
