// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resultado de la transcripción ASR. El audio nunca se persiste.
 */
export type AsrResponse = { text: string, duration_ms: number, model: string, };
