// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditId } from "./AuditId";
import type { SessionId } from "./SessionId";
import type { JsonValue } from "./serde_json/JsonValue";

export type AuditEntry = { id: AuditId, session_id?: SessionId | null, 
/**
 * tool_exec | llm_call | approval | config
 */
kind: string, detail: JsonValue, ts: string, };
