// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

/**
 * Filtros de GET /v1/audit.
 */
export type AuditQuery = { cursor?: string | null, limit?: number, session_id?: SessionId | null, provider?: string | null, };
