// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditEntry } from "./AuditEntry";

export type AuditPage = { entries: Array<AuditEntry>, next_cursor?: string | null, };
