// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateSessionRequest = { 
/**
 * Ruta absoluta a un directorio existente, sin secuencias de traversal.
 */
workspace_path: string, 
/**
 * Opcional, ≤ 120 caracteres.
 */
title?: string | null, };
