// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Catálogo cerrado de códigos de error de C-1.
 */
export type ErrorCode = "unauthorized" | "not_found" | "validation_failed" | "conflict" | "session_busy" | "asr_failed" | "internal";
