// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filtros de GET /v1/sessions/{id}/events.
 */
export type EventsQuery = { after_seq?: number, 
/**
 * Máximo 1000.
 */
limit?: number, };
