// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventEnvelope } from "./EventEnvelope";

export type EventsPage = { events: Array<EventEnvelope>, last_seq: number, has_more: boolean, };
