// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Disparador de un cambio de proveedor (C-3 `model_provider_changed`, C-4 tabla 6).
 */
export type FallbackTrigger = "oom" | "ttft_exceeded" | "failures" | "manual";
