// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identificador de un mensaje (usuario o asistente).
 */
export type MessageId = string;
