// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRef } from "./ModelRef";
import type { Thresholds } from "./Thresholds";

/**
 * Configuración primaria/fallback remota. El PUT aplica al siguiente turno.
 */
export type ModelConfig = { primary: ModelRef, fallback: ModelRef, thresholds: Thresholds, };
