// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalModelConfig } from "./ExternalModelConfig";
import type { FallbackConfig } from "./FallbackConfig";
import type { LocalModelConfig } from "./LocalModelConfig";
import type { ModelPolicy } from "./ModelPolicy";

/**
 * Política completa del adapter (C-1). El PUT reemplaza el objeto entero;
 * aplica a partir de la siguiente llamada al modelo, jamás interrumpe una
 * generación en curso.
 */
export type ModelConfig = { policy: ModelPolicy, local: LocalModelConfig, external: ExternalModelConfig, fallback: FallbackConfig, };
