// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutboxItem } from "./OutboxItem";

export type OutboxPage = { items: Array<OutboxItem>, };
