// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutboxTarget } from "./OutboxTarget";

/**
 * Una tarea en el buzón (GET /v1/outbox).
 */
export type OutboxItem = { id: string, target: OutboxTarget, 
/**
 * `queued` | `delivered` | `expired`.
 */
state: string, payload_kind: string, enqueued_at: string, expires_at: string, };
