// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identificador de una regla de auto-aprobación (RF-18).
 */
export type RuleId = string;
