// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SendMessageRequest = { 
/**
 * ≤ 32 000 caracteres.
 */
content: string, 
/**
 * UUID generado por el cliente; clave de idempotencia por sesión.
 */
client_msg_id: string, };
