// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "./MessageId";
import type { SessionState } from "./SessionState";

export type SendMessageResponse = { message_id: MessageId, session_state: SessionState, accepted_at: string, };
