// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estado de una sesión (C-1 / C-3).
 */
export type SessionState = "idle" | "running" | "waiting_approval" | "archived";
