// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionDto } from "./SessionDto";

export type SessionsPage = { sessions: Array<SessionDto>, next_cursor?: string | null, };
