// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionState } from "./SessionState";

/**
 * Filtros de GET /v1/sessions (paginación por cursor, filtro por estado).
 */
export type SessionsQuery = { cursor?: string | null, limit?: number, state?: SessionState | null, };
