// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PUT /v1/config/provider: configura o borra la API key de Groq.
 */
export type SetProviderKeyRequest = { 
/**
 * `null` o vacío borra la key (vuelve a modo degradado / a la del entorno).
 */
groq_api_key?: string | null, };
