// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Motivo de cierre de un mensaje del modelo (C-4 `StreamItem::Done`).
 */
export type StopReason = "end_turn" | "max_tokens" | "max_iterations" | "cancelled" | "error";
