// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalId } from "./ApprovalId";
import type { Decision } from "./Decision";
import type { SessionId } from "./SessionId";
import type { ToolCallId } from "./ToolCallId";
import type { JsonValue } from "./serde_json/JsonValue";

export type ApprovalDto = { id: ApprovalId, session_id: SessionId, tool_call_id: ToolCallId, tool: string, summary: string, args: JsonValue, decision?: Decision | null, resolved_by?: string | null, created_at: string, resolved_at?: string, };
