// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalId } from "./ApprovalId";
import type { Decision } from "./Decision";
import type { SessionId } from "./SessionId";

/**
 * Sobre v1 en dirección cliente → daemon. Es la misma forma que
 * [`crate::Envelope`] instanciada con [`Command`]; existe como struct propio
 * porque `ts-rs` solo permite fijar una instanciación concreta por genérico
 * (la otra es `EventEnvelope`). Sin `seq`: lo asigna el daemon al efecto.
 */
export type CommandEnvelope = { v: number, 
/**
 * Sesión objetivo (`send_message`); `null` en comandos globales.
 */
session_id: SessionId | null, ts: string, } & ({ "type": "send_message", "payload": { content: string, client_msg_id: string, } } | { "type": "resolve_approval", "payload": { approval_id: ApprovalId, decision: Decision, reason?: string | null, remember_rule?: boolean | null, } } | { "type": "subscribe_session", "payload": { session_id: SessionId, after_seq: number, } } | { "type": "unsubscribe_session", "payload": { session_id: SessionId, } });
