// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalId } from "./ApprovalId";
import type { Decision } from "./Decision";

export type DecisionResponse = { approval_id: ApprovalId, resolved: boolean, decision: Decision, resolved_by: string, resolved_at: string, };
