// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";

export type DecisionRequest = { decision: Decision, 
/**
 * Opcional, ≤ 500 caracteres.
 */
reason?: string | null, 
/**
 * Crear regla estable (RF-18).
 */
remember_rule?: boolean | null, };
