// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Una entrada de directorio (solo se listan carpetas: se elige el workspace).
 */
export type DirEntry = { name: string, 
/**
 * Ruta absoluta de la entrada.
 */
path: string, };
