// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntry } from "./DirEntry";

/**
 * Listado de un directorio para el selector de carpeta de la UI.
 */
export type DirListing = { 
/**
 * Ruta absoluta que se listó.
 */
path: string, 
/**
 * Directorio padre (`null` en una raíz).
 */
parent?: string | null, 
/**
 * Subdirectorios, ordenados por nombre.
 */
entries: Array<DirEntry>, };
