// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorBody } from "./ErrorBody";

/**
 * Única forma de error permitida: `{ "error": { code, message, details } }`.
 */
export type ErrorEnvelope = { error: ErrorBody, };
