// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalId } from "./ApprovalId";
import type { Decision } from "./Decision";
import type { FallbackTrigger } from "./FallbackTrigger";
import type { MessageId } from "./MessageId";
import type { ProviderId } from "./ProviderId";
import type { SessionId } from "./SessionId";
import type { SessionState } from "./SessionState";
import type { StopReason } from "./StopReason";
import type { ToolCallId } from "./ToolCallId";
import type { Usage } from "./Usage";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Sobre v1. `T` es `Event` (daemon → clientes) o `Command` (clientes → daemon).
 */
export type EventEnvelope = { v: number, 
/**
 * `null` en eventos globales (p. ej. `daemon_unavailable`).
 */
session_id: SessionId | null, 
/**
 * `Some` en eventos; `None` (omitido) en comandos.
 */
seq?: number, ts: string, } & ({ "type": "session_state", "payload": { state: SessionState, title?: string | null, reason?: string | null, } } | { "type": "message_delta", "payload": { message_id: MessageId, delta: string, } } | { "type": "message_completed", "payload": { message_id: MessageId, stop_reason: StopReason, usage: Usage, } } | { "type": "tool_call_requested", "payload": { tool_call_id: ToolCallId, tool: string, args: JsonValue, } } | { "type": "approval_request", "payload": { approval_id: ApprovalId, tool_call_id: ToolCallId, tool: string, summary: string, args: JsonValue, expires_at?: string, } } | { "type": "approval_resolved", "payload": { approval_id: ApprovalId, decision: Decision, resolved_by: string, } } | { "type": "tool_result", "payload": { tool_call_id: ToolCallId, ok: boolean, output_excerpt: string, truncated: boolean, } } | { "type": "file_diff", "payload": { tool_call_id: ToolCallId, path: string, diff_unified: string, additions: number, deletions: number, } } | { "type": "model_provider_changed", "payload": { from: ProviderId, to: ProviderId, trigger: FallbackTrigger, } } | { "type": "daemon_unavailable" } | { "type": "error", "payload": { code: string, message: string, fatal: boolean, } });
