// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Diff unificado de un archivo del workspace.
 */
export type FileDiff = { 
/**
 * Ruta relativa al workspace, tal como la pidió la herramienta.
 */
path: string, 
/**
 * Diff en formato unified (con encabezados `---`/`+++` y hunks `@@`).
 */
unified: string, additions: number, deletions: number, };
