// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderStatus } from "./ProviderStatus";
import type { RelayStatus } from "./RelayStatus";

export type HealthResponse = { status: string, version: string, provider: ProviderStatus, 
/**
 * Ausente en builds previos al relay; los clientes lo tratan opcional.
 */
relay?: RelayStatus, };
