// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Respuesta al encolar.
 */
export type OutboxAccepted = { outbox_id: string, 
/**
 * `queued` o `delivered` (entrega inmediata si el daemon estaba conectado).
 */
state: string, expires_at: string, };
