// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

/**
 * Destino de una tarea encolada: una sesión existente o una nueva.
 */
export type OutboxTarget = { 
/**
 * `null` = crear una sesión nueva al drenar.
 */
session_id?: SessionId | null, 
/**
 * Título de la sesión nueva (solo si `session_id` es null).
 */
new_session_title?: string | null, };
