// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutboxTarget } from "./OutboxTarget";

/**
 * POST /v1/outbox — encolar una tarea (equivale a un `send_message` diferido).
 * El buzón acepta SOLO mensajes; nada de aprobaciones ni control (ADR-007).
 */
export type OutboxRequest = { target: OutboxTarget, 
/**
 * `plaintext` (M2) o `sealed_box` (M3, cifrado para el daemon).
 */
payload_kind: string, 
/**
 * Texto del mensaje (o ciphertext base64 en `sealed_box`). ≤ 32 KB.
 */
payload: string, 
/**
 * UUID de idempotencia (como en `send_message`).
 */
client_msg_id: string, };
