// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionState } from "./SessionState";

/**
 * PATCH /v1/sessions/{id}: archivar / renombrar. Reemplazo por campo presente.
 */
export type PatchSessionRequest = { title?: string | null, 
/**
 * Único cambio de estado permitido por API: `archived`.
 */
state?: SessionState | null, };
