// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estado de la API key del proveedor. Nunca expone la key en sí (RNF-07);
 * solo si hay una configurada y de dónde vino.
 */
export type ProviderKeyStatus = { 
/**
 * Hay una API key efectiva (la app puede llamar al modelo).
 */
configured: boolean, 
/**
 * `stored` (persistida desde la UI), `env` (variable de entorno) o `none`.
 */
source: string, };
