// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identificador estable de un proveedor de modelo para el audit log (RF-22).
 * No es un ULID: es un nombre jerárquico legible, p. ej. `local:vllm:qwen3.5-8b`.
 */
export type ProviderId = string;
