// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewRule } from "./NewRule";

/**
 * PUT /v1/rules: reemplazo completo del conjunto.
 */
export type PutRulesRequest = { rules: Array<NewRule>, };
