// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estado de la conexión saliente al relay C-2 (ADR-006).
 */
export type RelayStatus = { 
/**
 * `RUTSUBO_RELAY_URL` está configurada.
 */
configured: boolean, 
/**
 * La conexión WebSocket saliente está viva.
 */
connected: boolean, };
