// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleId } from "./RuleId";

export type Rule = { id: RuleId, workspace_path: string, tool: string, pattern: string, created_at: string, };
