// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";
import type { SessionState } from "./SessionState";

/**
 * Detalle con contadores (GET /v1/sessions/{id}).
 */
export type SessionDetail = { message_count: number, pending_approvals: number, id: SessionId, workspace_path: string, title: string, state: SessionState, created_at: string, last_seq: number, };
