// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Thresholds = { ttft_threshold_ms: number, failure_window: number, cooldown_s: number, };
