// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conteo de tokens de una generación (RF-22, RF-31).
 */
export type Usage = { prompt_tokens: number, completion_tokens: number, };
