// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * El navegador no puede mandar `Authorization` en el handshake WS y el proxy
 * BFF (serverless) no reenvía WebSockets: el cliente remoto pide un ticket
 * efímero por REST (autenticado vía BFF) y abre el WS directo al daemon con
 * `?ticket=`. Un solo uso, caduca en `expires_in_s` segundos.
 */
export type WsTicketResponse = { ticket: string, expires_in_s: number, };
